# Generated by Django 2.2.4 on 2019-08-30 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190828_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 30, 11, 43, 32, 579066, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
