# Generated by Django 2.2.4 on 2019-08-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0004_auto_20190830_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='selected',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answered_to_question', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='user',
        ),
    ]
