# Generated by Django 2.2.4 on 2019-08-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_requestedpoll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedpoll',
            name='uuid',
        ),
        migrations.AddField(
            model_name='requestedpoll',
            name='url',
            field=models.CharField(default='a27ab5d0458f488899a2b706243c9bec', max_length=72),
        ),
    ]
