# Generated by Django 2.2.4 on 2019-08-30 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0008_auto_20190830_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedpoll',
            name='url',
            field=models.CharField(default='a8aa7088216942a5bedc372ffd92c225', editable=False, max_length=72),
        ),
        migrations.AlterUniqueTogether(
            name='requestedpoll',
            unique_together={('user', 'poll')},
        ),
    ]
