# Generated by Django 2.2.4 on 2019-08-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20190830_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedpoll',
            name='url',
        ),
        migrations.AddField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='f46dea87a3c24b1b927cbfb68dfe17ce', editable=False, max_length=72),
        ),
    ]
