# Generated by Django 2.2.4 on 2019-09-02 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20190830_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedpoll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 2, 11, 21, 2, 340565, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='b00b628e534e400691ebba023596ca0a', editable=False, max_length=72),
        ),
    ]
