# Generated by Django 2.2.4 on 2019-09-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20190902_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='questions_answers',
            field=models.ManyToManyField(related_name='poll_answer', to='poll.QuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='6ab16d78745e41f1b5d858737f8ba9d0', editable=False, max_length=72),
        ),
    ]
