# Generated by Django 2.2.4 on 2019-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20190904_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='question', to='poll.Choice'),
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='faa40a40b0c540e5bd5842b8f8cae10b', editable=False, max_length=72),
        ),
    ]
