# Generated by Django 2.2.4 on 2019-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20190906_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('-question',)},
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='ffd433db2bfa48c0ada9c2e74be7014b', editable=False, max_length=72),
        ),
    ]
