# Generated by Django 2.2.4 on 2019-09-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20190911_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('position', 'created')},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('question',)},
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='bc1d7a2691f746b6bfab8df139cc130a', editable=False, max_length=72),
        ),
    ]
