# Generated by Django 2.2.4 on 2019-10-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_auto_20191010_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetranslation',
            name='language_code',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=25),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='language_code',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=25),
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='3b152fdb48314a8682d15eb5f2499c3b', editable=False, max_length=72),
        ),
        migrations.CreateModel(
            name='PollTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=25)),
                ('translation', models.CharField(max_length=250)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='poll.Poll')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
