# Generated by Django 2.2.4 on 2019-10-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_auto_20191010_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='b34898e751df4b3fb27d284cf781df41', editable=False, max_length=72),
        ),
        migrations.CreateModel(
            name='PollAnswersThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.QuestionAnswer')),
            ],
        ),
    ]
