# Generated by Django 2.2.4 on 2019-10-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_auto_20191014_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollAnswersThrough',
            new_name='PollAnswerThrough',
        ),
        migrations.RemoveField(
            model_name='pollanswerthrough',
            name='poll',
        ),
        migrations.AddField(
            model_name='pollanswerthrough',
            name='poll_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.PollAnswer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='b364b60323d743aca6fee151b8db333c', editable=False, max_length=72),
        ),
    ]
