# Generated by Django 2.2.4 on 2019-10-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0023_auto_20191014_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='a68627b0fd6245258f66415024caeda8', editable=False, max_length=72),
        ),
        migrations.DeleteModel(
            name='PollAnswerThrough',
        ),
    ]
