# Generated by Django 2.2.4 on 2019-10-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_auto_20191014_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedpoll',
            name='url_param',
            field=models.CharField(default='4163639ffb6d4b8fa1bb8cca8c79c582', editable=False, max_length=72),
        ),
    ]
